// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xlgnecxamzbjstfxpxmy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhsZ25lY3hhbXpianN0ZnhweG15Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc1NzM3MTMsImV4cCI6MjA2MzE0OTcxM30.Bun7XGRSHE_hfDD9qz3J9GvSuYDS8KV2uMiRpcunQqY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);